### ISSUE TITLE
Some feature suggestions

### ISSUE THREAD

**Issue by ScottDaybreak** [axel358/smartdock#68] opened 2023-08-02 00:14 UTC
I'm not sure if this is still updated but I just felt like giving some feedback as I love the dock but it's not perfect.

* Add an option so when a keyboard shows up the dock hides itself and rereveals itself after the keyboard disappears as the dock blocks parts of it when it does happen. As well as a potential option to have the dock to automatically show up on the home screen.
* An option to customise the position of the dock. On my screen the dock covers up a lot of things near the bottom so I'd appreciate an option to just lower the dock position a tiny bit
* An option to centre the navigation buttons so their perfectly on the middle. I don't use the option to show recent apps because they are broken for me and they are all bunched up together and messed up so I just use the navigation buttons but the buttons are slightly off centre so it messes with my muscle memory so I'd appreciate an option to adjust it unless I missed an option for it.
* And one last suggestion. Maybe there could be an option to swipe up on the middle part of the dock when it's already open so you can switch to a home screen dock instead so instead of the navigational buttons it has the 4 (Or more) apps you select to have easy access to.

These are all the suggestions I have. Over all even with the shortcomings I enjoy the app ❤️

**Comment by axel358** [comment] 2024-02-14 10:03
Since the first suggestion is a duplicate of #103 and the rest have been fixed on master I'll be closing this

**Closed by axel358** 2024-02-14 10:03 UTC
Labels: enhancement
