### ISSUE TITLE
Some issues and suggestions 

### ISSUE THREAD

**Issue by KamrulShahed** [axel358/smartdock#158] opened 2024-04-28 21:42 UTC
Issues:
1. App crashed and kept crashing in loop when i accidentally pressed ok leaving icon pading box empty.
2. App gets stuck when i used high number of recent app number
3. Recent apps in dock goes to oldest recent apps each time i open an app. Its inconvenient to scroll again and again to the latest recent apps. It should stay at latest always. Its an urgent fix. I cant use more than 6 recent app with centered option enabled or disabled both. If enabled icons overlap and same problem hoppens. If disabled then also this problem happens. I mean goes back to oldest recent apps eatch time i open an app. Same happens when screen goes of or doc gets hidden. I think the recent app list gets refreshed each time i do these works and goes back to the oldest apps. I dont know whether its a feature. If so its need to be changed. Peaple need most recent apss more than old recent apps.
4. Icon label in dock seems not working 
5.  Search in app menu is buggy. Sometimes it doesnt start searching and sometimes it stops searching when im typing and starts showing all apps. 

Suggestions: 
1. Apps menu button should start a inbuilt soft keyboard automatically when i press it. It will save time of searching and launching apps. An option would be great to choose from between whether to open keyboard automatically at app menu click.  Or an option to add search icon in doc like back recent home buttons. Or at least search field at bottom so that reaching it gets easier with one hand operation. 
2. Uninstall, clear from recent (close app) and app info option in long pressing icon in dock. 
3. App sorting option in app menu by date and reversed. It will make it easy to find latest and oldest installed apps.
4. Icon pack support
6.  Search should start at first key stroke. Now its starts showing results after typing 2 letters. 
7.  When using as default launcher home button brings to app settings not home when app settings is opend in background. I have to go back to bring home. Home and app settings should be separated.

**Comment by KamrulShahed** [comment] 2024-05-01 12:27
I dont need other fix and suggestions urgently. But only recent apps getting to older apps in each app launch is bothering me. I appreciate the decision to put latest recent apps at right side of screen. It helps right handed operation. And if you can fix the problem of slight hanging (delay in operation like opening app menu or scrolling recent apps) when using high number of recent apps. Its even starts happening at 10 or 15 apps. And becomes worse with the increasing of the apps. But i can tolerate this hanging for a while by selecting less number of apps in dock. Just fix the problem of going back to older recent apps with each refresh problem.

**Comment by axel358** [comment] 2024-09-22 15:08
I'll be closing this, issues are supposed to describe one problem at the time, having more than one  in a single issue makes it hard to track and close them. Also before opening a new issue please make sure that it isn't a duplicate of an existing issue

**Closed by axel358** 2024-09-22 15:08 UTC
