### ISSUE TITLE
Custom ordering for optional buttons

### ISSUE THREAD

**Issue by KeronCyst** [axel358/smartdock#179] opened 2024-10-16 19:49 UTC
Does anyone know if there is a way to reorder the back and home button locations? I'd like to swap them if possible.

It would be nice if they could be modularly adjusted just through the checkboxes, based on which ones you tick first/last.

**Comment by axel358** [comment] 2024-11-23 15:54
Duplicate of #142

**Closed by axel358** 2024-11-23 15:54 UTC
