### ISSUE TITLE
Settings SmartDock as default launcher causes the current launcher to crash

### ISSUE THREAD

**Issue by JUDE122-MAX** [axel358/smartdock#63] opened 2023-07-05 11:17 UTC
Anytime I want to set the app as my default launcher it crashes. Note mg Phone is not rooted and I use gesture navigation (android 12)

**Comment by axel358** [comment] 2023-07-05 17:19
Device brand?

**Comment by Kabouik** [comment] 2023-07-25 08:50
Not sure if related, but on my end, Smartdock was crashing after I granted it permissions to show notifications, but hadn't figured out how to grant it the "Accessibility service" permissions. I had to clear the application storage (long tap on the Smartdock icon) to grant those permissions together, or at least remove the notifications permissions if the other one was not granted, in order to make Smartdock run normally.

I am using a F(x)tec Pro1, running Droidian, and Waydroid with `lineage_waydroid_arm64_userdebug 11 RQ3A.211001.001 48 test-keys`.

**Comment by axel358** [comment] 2023-07-25 10:24
@Kabouik There is  a reason why those permissions are in that particular order

**Comment by Kabouik** [comment] 2023-07-25 10:58
Yup, I just couldn't figure out how to grant the Accessibility ones so I enabled all I could first, and then noticed that issue. Not complaining about it, just mentioning in case the OP would be in the same situation.

**Comment by axel358** [comment] 2023-08-16 22:43
This might have been fixed here, please give it a try https://github.com/axel358/smartdock/suites/15163236007/artifacts/866497365

**Comment by axel358** [comment] 2023-10-04 14:07
Closing this as completed since im not able to reproduce it and there has not been any feedback from @JUDE122-MAX. Feel free to reopen it if the issue still persists

**Closed by axel358** 2023-10-04 14:07 UTC
Labels: bug
