### ISSUE TITLE
When using keyboard, dock not moving top of the keyboard and blocking keyboard keys

### ISSUE THREAD

**Issue by they10** [axel358/smartdock#103] opened 2023-10-16 13:41 UTC
When I search on the app menu, dock moving top of the keyboard and not blocking the keyboard keys. But when I use the keyboard on the other apps, dock stay on the bottom, and I can't access space key, enter and other keys, is there a way to fix this issue? Thank you for your help. And its a great app by the way.

**Comment by Pablo1107** [comment] 2023-12-15 18:00
I have the same issue. ![Screenshot_20231215_145908_GitHub.jpg](https://github.com/axel358/smartdock/assets/17091659/1c2d2fb1-93d4-4742-9a0a-8c0b6d419428)

**Comment by Pablo1107** [comment] 2023-12-15 18:00
It would be good if the app can act as a nav bar and reserve space for it.

**Comment by axel358** [comment] 2024-02-26 11:11
https://github.com/axel358/smartdock/actions/runs/8047899734
Could u guys check if this is still present on this build. I'm not able to reproduce this on A13

**Comment by Pablo1107** [comment] 2024-02-26 12:41
> https://github.com/axel358/smartdock/actions/runs/8047899734
> Could u guys check if this is still present on this build. I'm not able to reproduce this on A13

![Screenshot_20240226_094005_Firefox.jpg](https://github.com/axel358/smartdock/assets/17091659/e88b6b60-8cc7-4ca3-bc80-8f4dac6067f7)

Stills happens on that debug apk.

**Comment by Pablo1107** [comment] 2024-02-26 12:45
> Android version?

Android 13, Samsung One UI 5.1 if that matters.

**Comment by axel358** [comment] 2024-02-26 13:14
Ah I understand now. Unfortunately that's how application overlays work. They draw on top of pretty much everything. The only work around for this is that since a12.1 the dock can draw on top of Android's nav bar. That is if you use button navigation and set the dock height to minimum the space taken by the dock will be similar to the nav bars height thus not overlapping application contents. Closing this as a technical limitation

**Closed by axel358** 2024-02-26 13:14 UTC
Labels: bug

**Comment by atikattar1104** [comment] 2025-04-20 20:59
Would Like To Add, Dock Moves Above When Typing In Dock's App Drawer's Search, Then Restores Back To Normal.
